USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_COOKING_TIME_MIN_VALUE = 1
RECIPE_COOKING_TIME_MAX_VALUE = 10000

RECIPE_INGREDIENT_AMOUNT_MIN_VALUE = 1
RECIPE_INGREDIENT_AMOUNT_MAX_VALUE = 10000

AVATAR_UPLOAD_PATH = 'avatar/icons/'
RECIPE_IMAGE_UPLOAD_PATH = 'recipes/images/'


MAX_RECIPES_LIMIT = 10**10
