# Generated by Django 5.2 on 2025-04-23 14:40

from django.db import migrations
import json
import os
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile
from config.settings import BASE_DIR


def load_data(apps, schema_editor):
    SiteUser = apps.get_model('core', 'SiteUser')
    Ingredient = apps.get_model('core', 'Ingredient')
    Recipe = apps.get_model('core', 'Recipe')
    RecipeIngredient = apps.get_model('core', 'RecipeIngredient')
    Favorite = apps.get_model('core', 'Favorite')
    ShopCart = apps.get_model('core', 'ShopCart')
    Subscription = apps.get_model('core', 'Subscription')
    test_data_path = os.path.join(
        BASE_DIR,
        'data',
        'test_data.json'
    )
    with open(test_data_path, 'r', encoding='utf-8') as file:
        data = json.load(file)

    for entry in data:
        model = entry['model'].split('.')[-1]
        fields = entry['fields']
        pk = entry['pk']

        if model == 'siteuser':
            fields['password'] = make_password(fields['password'])
            SiteUser.objects.create(
                id=pk,
                username=fields['username'],
                email=fields['email'],
                first_name=fields['first_name'],
                last_name=fields['last_name'],
                password=fields['password'],
                avatar=fields['avatar']
            )

        elif model == 'ingredient':
            Ingredient.objects.create(
                id=pk,
                name=fields['name'],
                measurement_unit=fields['measurement_unit']
            )

        elif model == 'recipe':
            # image = ContentFile(b'', name=fields['image'])

            Recipe.objects.create(
                id=pk,
                author=SiteUser.objects.get(id=fields['author']),
                name=fields['name'],
                image=fields['image'],
                text=fields['text'],
                cooking_time=fields['cooking_time'],
                pub_date=fields['date_published']
            )

        elif model == 'recipeingredient':
            RecipeIngredient.objects.create(
                id=pk,
                recipe=Recipe.objects.get(id=fields['recipe']),
                ingredient=Ingredient.objects.get(id=fields['ingredient']),
                amount=fields['amount']
            )

        elif model == 'favorite':
            Favorite.objects.create(
                id=pk,
                user=SiteUser.objects.get(id=fields['user']),
                recipe=Recipe.objects.get(id=fields['recipe'])
            )

        elif model == 'shoppingcart':
            ShopCart.objects.create(
                id=pk,
                user=SiteUser.objects.get(id=fields['user']),
                recipe=Recipe.objects.get(id=fields['recipe'])
            )

        elif model == 'subscription':
            Subscription.objects.create(
                id=pk,
                user=SiteUser.objects.get(id=fields['user']),
                author=SiteUser.objects.get(id=fields['author'])
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
