name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Install Flake8
        run: pip install flake8
        
      - name: Run Flake8
        run: flake8 ./backend/

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Вход в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка и отправка Backend
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: |
            ruskiy/foodgram_backend:latest
            ruskiy/foodgram_backend:${{ github.sha }}

      # Сборка и отправка Frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: |
            ruskiy/foodgram_frontend:latest
            ruskiy/foodgram_frontend:${{ github.sha }}